name: Pre-Commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit checks ALL
      run: pre-commit run --all-files
    - name: Get changed files
      id: changed_files
      run: |
        echo "files="$(
          git diff --name-only ${{ github.event.pull_request.base.sha }}...HEAD
        ) >> $GITHUB_OUTPUT
    - name: Run pre-commit checks
      run: |
        pre-commit run ${{ steps.changed_files.outputs.files }}
