name: main

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  main:
    uses: asottile/workflows/.github/workflows/tox.yml@v1.0.0
    with:
      env: '["py39"]'
      # TODO: remove this line
      os: ubuntu-latest
